### ISSUE TITLE
This didn't fix my mic problem

### ISSUE THREAD

**Issue by erickmufath** [reiryuki/Mic-Fix-Magisk-Module#3]
When installing this there is no difference. In quiet conditions, the recording results do not produce any buzzing or static noise. But when I started to make a sound, it was there(like ssss sound, even with wired earphone with USB-C which had no issues on my previous device). Do you have any idea about this? Btw I am using mediatek device.

**Comment by reiryuki** [comment]
I'm sorry, I don't know
